# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 19, 15, 28, 29, 178154, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 19, 15, 28, 36, 816957, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
