# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160104_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='published_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 4, 9, 43, 30, 777610)),
            preserve_default=False,
        ),
    ]
